spring:
  profiles:
    active: prod
info:
  map:
    artifactId: '@artifactId@'
    projectName: '@project.name@'
    version: '@project.version@'
    buildName: '@project.build.finalName@'
    runtimeName: '@java.runtime.name@'
    runtimeVersion: '@java.runtime.version@'
    buildTime: '@timestamp@'

secret:
  key: G242nUlMmiT1tcToX29xkg==
  enabled: true
